### ISSUE TITLE
Shell Subprocess Does Not Inherit Parent Environment.

### ISSUE THREAD

**Issue by MikuAuahDark** [pfirsich/makelove#28]
https://github.com/pfirsich/makelove/blob/82e06917373fd6bb6a36d6b2e3789c36828cc7c4/makelove/hooks.py#L32

The `env=env` **completely overwrites** the new environment of the shell with new environment variables specified at `env`. This means no `PATH` either.

What should be done is `env={**os.environ, **env}` instead.

**Comment by josh-perry** [comment]
Should be fixed now.

This:
```toml
[hooks]
prebuild = [
    "python -c \"print('hi')\""
]
```
works for me now at the very least.
